### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dotellie** [kittykatattack/smoothie#1]
I'm not an expert of any kind on this kind of stuff, but I'm fairly certain that by not including a license notice in your project, it's running on the standard copyright laws.

This is a shame since I can't redistribute the code in that case. I would really like to use this for my next project since it looks to be exactly what I need, except I won't have to do all the hard work myself.

Any possibility of you adding a license notice or did you have something else in mind with not including it in the first place?

Again, not an expert on copyright laws, I just want to use smoothie in my project. :D

**Comment by kittykatattack** [comment]
Hi!

No worries: "Smoothie is 100% unlicensed and free to use for anything under any circumstance, for now and for ever."

I'm pretty sure that for legal purposes this statement by me, the creator of the work, is all you need.

-kk.

**Comment by dotellie** [comment]
I see. Thank you very much for your reply!

I would still suggest you add a little license notice with exactly the statement you wrote there, just so that anyone who looks at your project is immediately aware. That's just a suggestion though.

Anyway, thank you very much for making smoothie! I'm totally in love with it and pixi right now! <3
