### ISSUE TITLE
Detrimental performance on mobile devices

### ISSUE THREAD

**Issue by darren-dev** [kittykatattack/smoothie#4]
While this library works amazingly on desktop browsers, there is quite the performance decrease in mobile devices.

I've benchmarked this on 15 individual animations playing simultaneously (Off a 90 sized sprite sheet); on the standard game loop, an individual smoothie loop for every animation, as well as one smoothie loop playing all the animations at once.

My results are as follows:

- **Standard:** Fluid movement and no frame rate loss
- **Individual Smoothie:** Around 10-15 FPS loss with noticeable slowness
- **Combined Smoothie** Around 20-30 FPS loss with noticeable slowness and frame loss

The above was tested on Samsung Note 4 (Android), Sony Xperia (Android), iPhone5 (iOS), iPhone 5S (iOS)

Let me know if you have any additional queries

**Comment by kittykatattack** [comment]
Can anyone comment on whether this is a problem with Smoothie's code or Pixi's renderer?

**Comment by kittykatattack** [comment]
Closed until more information is forthcoming.

**Comment by advancedsoftwarecanada** [comment]
I can confirm that it SEEMS like animation with Smoothie on mobile might seem poor. However, after a lot of spent time optimizing my game, turns out it runs GREAT on mobile devices.

Smoothie is awesome.

www.StarCommanderOnline.com to check mobile performance for yourself.

**Comment by kittykatattack** [comment]
That's great to hear, thanks so much for letting us know!
